defmodule Localfinds.Finds.Feedback do
  @moduledoc """
  Write schema for `localfinds.feedback` — the taste signal the agents read.

  Unlike `Find`, this one is inserted by the web, so the primary key is
  autogenerated: the column is `GENERATED ALWAYS AS IDENTITY`, and Ecto must
  leave it out of the INSERT and read it back. `created_at` is filled by the
  column default.
  """
  use Ecto.Schema

  @primary_key {:id, :id, autogenerate: true}
  @schema_prefix "localfinds"
  schema "feedback" do
    field :find_id, :integer
    field :action, :string
    field :note, :string
    field :created_at, :utc_datetime
  end

  @type t :: %__MODULE__{}
end
