defmodule LocalfindsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :localfinds

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # secure: true always: browsers exempt http://localhost in dev; behind
  # nginx in prod the scheme is https.
  @session_options [
    store: :cookie,
    key: "_localfinds_key",
    signing_salt: "tb6TKHK2",
    same_site: "Lax",
    secure: true
  ]

  # Trust X-Forwarded-Proto from nginx so conn.scheme is :https behind the
  # proxy — otherwise Plug sees :http and won't default `secure: true`
  # cookies on (session cookie sets it explicitly, but this keeps
  # conn.scheme itself correct generally).
  plug Plug.RewriteOn, [:x_forwarded_proto]

  socket "/auth/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]]

  # Serve LiveView/HTML assets at /auth/assets so nginx routing to the
  # Phoenix app stays a single /auth/ location block.
  plug Plug.Static,
    at: "/auth/assets",
    from: {:localfinds, "priv/static/assets"},
    gzip: false

  plug Plug.Session, @session_options

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :localfinds,
    gzip: not code_reloading?,
    only: LocalfindsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :localfinds
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug LocalfindsWeb.Router
end
